
import React,{useState,useEffect} from 'react';
import {Search,Download} from 'lucide-react';
import {api} from '../hooks/api.js';
const PLATFORMS=['365','docusign','lucid','bitbucket','jira','google'];
const PL={'365':'Microsoft 365',docusign:'DocuSign',lucid:'Lucid',bitbucket:'Bitbucket',jira:'Jira',google:'Google Workspace'};
const PC={'365':'#1e5fad',docusign:'#7c3aed',lucid:'#d97706',bitbucket:'#059669',jira:'#0284c7',google:'#dc2626'};
const RiskBadge=({level})=>{const m={high:['var(--red)','var(--red-bg)','ALTO'],medium:['var(--yellow)','var(--yellow-bg)','MÉDIO'],low:['var(--green)','var(--green-bg)','BAIXO']};const[color,bg,text]=m[level]||['var(--text3)','var(--bg3)',level];return<span style={{padding:'2px 8px',borderRadius:4,fontSize:'0.65rem',fontWeight:700,fontFamily:'var(--font-mono)',background:bg,color}}>{text}</span>;};
function exportCSV(data,filename){if(!data.length)return;const h=Object.keys(data[0]);const rows=data.map(r=>h.map(k=>`"${(r[k]||'').toString().replace(/"/g,'""')}"`).join(','));const blob=new Blob([[h.join(','),...rows].join('\n')],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url);}
export default function Users(){
  const[tab,setTab]=useState('risk');const[search,setSearch]=useState('');const[platform,setPlatform]=useState('');const[data,setData]=useState([]);const[loading,setLoading]=useState(false);const[azureList,setAzureList]=useState([]);const[azureLoading,setAzureLoading]=useState(false);
  const load=async()=>{setLoading(true);try{const p=new URLSearchParams();if(search)p.append('search',search);if(platform)p.append('platform',platform);const ep=tab==='risk'?'/users/risk':'/users/terminated';setData(await api.get(`${ep}?${p}`,{noCache:true}));}catch{setData([]);}finally{setLoading(false);}}
  const loadAzure=async()=>{setAzureLoading(true);try{const r=await api.get('/users/risk',{noCache:true});setAzureList(r.map(u=>({email:u.email,nome:u.name||'',departamento:u.department||'',plataformas:(u.active_platforms||[]).join('; ')})));}catch{setAzureList([]);}finally{setAzureLoading(false);}};
  useEffect(()=>{load();},[tab,platform]);
  return<div style={{animation:'fadeIn 0.3s ease'}}>
    <div style={{marginBottom:'1.75rem'}}><h1 style={{fontWeight:700,fontSize:'1.5rem',color:'var(--text)'}}>Usuários</h1><p style={{color:'var(--text2)',fontSize:'0.85rem',marginTop:3}}>Desligados e seus acessos ativos por plataforma</p></div>
    <div style={{display:'flex',gap:'0.4rem',marginBottom:'1.25rem',background:'var(--bg3)',padding:'0.3rem',borderRadius:'var(--radius)',width:'fit-content',border:'1px solid var(--border)'}}>
      {[{id:'risk',label:'Com acesso ativo'},{id:'all',label:'Todos desligados'},{id:'azure',label:'Exportar Azure'}].map(t=><button key={t.id} onClick={()=>{setTab(t.id);if(t.id==='azure')loadAzure();}} style={{padding:'0.45rem 1rem',borderRadius:6,fontSize:'0.82rem',fontWeight:tab===t.id?600:400,background:tab===t.id?'var(--bg2)':'transparent',border:tab===t.id?'1px solid var(--border)':'1px solid transparent',color:tab===t.id?'var(--accent)':'var(--text2)',boxShadow:tab===t.id?'var(--shadow-sm)':'none'}}>{t.label}</button>)}
    </div>
    {tab==='azure'&&<div style={{background:'var(--bg2)',border:'1px solid var(--border)',borderRadius:'var(--radius-lg)',boxShadow:'var(--shadow-sm)'}}>
      <div style={{padding:'1.25rem 1.5rem',borderBottom:'1px solid var(--border)',display:'flex',justifyContent:'space-between',alignItems:'center'}}>
        <div><h2 style={{fontSize:'0.9rem',fontWeight:600}}>Lista para Desativação no Azure</h2><p style={{fontSize:'0.78rem',color:'var(--text2)',marginTop:2}}>Desligados com acesso ativo — para desativar no Azure AD</p></div>
        <button onClick={()=>exportCSV(azureList,'desativar-azure.csv')} disabled={!azureList.length} style={{display:'flex',alignItems:'center',gap:'0.4rem',padding:'0.5rem 1rem',background:'var(--accent)',border:'none',borderRadius:'var(--radius)',color:'#fff',fontWeight:600,fontSize:'0.82rem',opacity:azureList.length?1:0.5}}><Download size={14}/>Exportar CSV</button>
      </div>
      <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:'0.82rem'}}>
        <thead><tr style={{background:'var(--bg3)'}}>{['Email','Nome','Departamento','Plataformas com Acesso'].map(h=><th key={h} style={{padding:'0.65rem 1rem',textAlign:'left',color:'var(--text2)',fontSize:'0.72rem',fontWeight:600,textTransform:'uppercase',letterSpacing:0.7}}>{h}</th>)}</tr></thead>
        <tbody>{azureLoading?<tr><td colSpan={4} style={{textAlign:'center',padding:'2.5rem',color:'var(--text3)'}}>Carregando...</td></tr>:azureList.length===0?<tr><td colSpan={4} style={{textAlign:'center',padding:'2.5rem',color:'var(--green)',fontSize:'0.85rem'}}>✓ Nenhuma conta a desativar</td></tr>:azureList.map((u,i)=><tr key={i} style={{borderTop:'1px solid var(--border)'}} onMouseEnter={e=>e.currentTarget.style.background='var(--blue-50)'} onMouseLeave={e=>e.currentTarget.style.background='transparent'}><td style={{padding:'0.7rem 1rem',fontFamily:'var(--font-mono)',fontSize:'0.75rem',color:'var(--text2)'}}>{u.email}</td><td style={{padding:'0.7rem 1rem',fontWeight:500}}>{u.nome||'—'}</td><td style={{padding:'0.7rem 1rem',color:'var(--text2)'}}>{u.departamento||'—'}</td><td style={{padding:'0.7rem 1rem',color:'var(--text2)',fontSize:'0.75rem',fontFamily:'var(--font-mono)'}}>{u.plataformas||'—'}</td></tr>)}</tbody>
      </table></div>
      <div style={{padding:'0.65rem 1rem',borderTop:'1px solid var(--border)',fontSize:'0.72rem',color:'var(--text3)'}}>{azureList.length} contas</div>
    </div>}
    {tab!=='azure'&&<>
      <div style={{display:'flex',gap:'0.6rem',marginBottom:'1rem'}}>
        <div style={{position:'relative',flex:1}}><Search size={14} color="var(--text3)" style={{position:'absolute',left:10,top:'50%',transform:'translateY(-50%)'}}/><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Buscar por e-mail ou nome..." style={{width:'100%',padding:'0.6rem 0.75rem 0.6rem 2.1rem',background:'var(--bg2)',border:'1px solid var(--border)',borderRadius:'var(--radius)',color:'var(--text)',fontSize:'0.82rem',outline:'none',boxShadow:'var(--shadow-sm)'}} onFocus={e=>e.target.style.borderColor='var(--accent)'} onBlur={e=>e.target.style.borderColor='var(--border)'}/></div>
        {tab==='risk'&&<select value={platform} onChange={e=>setPlatform(e.target.value)} style={{padding:'0.6rem 0.75rem',background:'var(--bg2)',border:'1px solid var(--border)',borderRadius:'var(--radius)',color:'var(--text)',fontSize:'0.82rem',outline:'none',boxShadow:'var(--shadow-sm)'}}><option value="">Todas plataformas</option>{PLATFORMS.map(p=><option key={p} value={p}>{PL[p]}</option>)}</select>}
        <button onClick={()=>exportCSV(data.map(u=>tab==='risk'?{email:u.email,nome:u.name,departamento:u.department,desligamento:u.termination_date,plataformas:(u.active_platforms||[]).join(';'),risco:u.risk_level}:{email:u.email,nome:u.name,departamento:u.department,desligamento:u.termination_date}),`${tab}-${new Date().toISOString().slice(0,10)}.csv`)} style={{display:'flex',alignItems:'center',gap:'0.4rem',padding:'0.6rem 0.9rem',background:'var(--bg2)',border:'1px solid var(--border)',borderRadius:'var(--radius)',color:'var(--text2)',fontSize:'0.82rem',boxShadow:'var(--shadow-sm)'}}><Download size={13}/>CSV</button>
      </div>
      <div style={{background:'var(--bg2)',border:'1px solid var(--border)',borderRadius:'var(--radius-lg)',boxShadow:'var(--shadow-sm)'}}>
        <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:'0.82rem'}}>
          <thead><tr style={{background:'var(--bg3)'}}>{(tab==='risk'?['Email','Nome','Departamento','Desligamento','Plataformas Ativas','Risco']:['Email','Nome','Departamento','Desligamento','Importado em']).map(h=><th key={h} style={{padding:'0.65rem 1rem',textAlign:'left',color:'var(--text2)',fontSize:'0.72rem',fontWeight:600,textTransform:'uppercase',letterSpacing:0.7,whiteSpace:'nowrap'}}>{h}</th>)}</tr></thead>
          <tbody>{loading?<tr><td colSpan={6} style={{textAlign:'center',padding:'2.5rem',color:'var(--text3)'}}>Carregando...</td></tr>:data.length===0?<tr><td colSpan={6} style={{textAlign:'center',padding:'2.5rem',color:tab==='risk'?'var(--green)':'var(--text3)',fontSize:'0.85rem'}}>{tab==='risk'?'✓ Nenhum usuário desligado com acesso ativo':'Nenhum usuário encontrado'}</td></tr>:data.map((u,i)=><tr key={i} style={{borderTop:'1px solid var(--border)',transition:'background 0.1s'}} onMouseEnter={e=>e.currentTarget.style.background='var(--blue-50)'} onMouseLeave={e=>e.currentTarget.style.background='transparent'}><td style={{padding:'0.7rem 1rem',fontFamily:'var(--font-mono)',fontSize:'0.75rem',color:'var(--text2)'}}>{u.email}</td><td style={{padding:'0.7rem 1rem',fontWeight:500}}>{u.name||'—'}</td><td style={{padding:'0.7rem 1rem',color:'var(--text2)'}}>{u.department||'—'}</td><td style={{padding:'0.7rem 1rem',fontFamily:'var(--font-mono)',fontSize:'0.75rem'}}>{u.termination_date||'—'}</td>{tab==='risk'?<><td style={{padding:'0.7rem 1rem'}}><div style={{display:'flex',gap:4,flexWrap:'wrap'}}>{(u.active_platforms||[]).map(p=><span key={p} style={{padding:'2px 7px',borderRadius:4,fontSize:'0.65rem',fontFamily:'var(--font-mono)',background:`${PC[p]||'#888'}15`,color:PC[p]||'var(--text2)',border:`1px solid ${PC[p]||'#888'}30`}}>{PL[p]||p}</span>)}</div></td><td style={{padding:'0.7rem 1rem'}}><RiskBadge level={u.risk_level}/></td></>:<td style={{padding:'0.7rem 1rem',fontFamily:'var(--font-mono)',fontSize:'0.75rem',color:'var(--text3)'}}>{u.imported_at?.slice(0,16)||'—'}</td>}</tr>)}</tbody>
        </table></div>
        <div style={{padding:'0.65rem 1rem',borderTop:'1px solid var(--border)',fontSize:'0.72rem',color:'var(--text3)',fontFamily:'var(--font-mono)'}}>{data.length} registros</div>
      </div>
    </>}
  </div>;
}
